main/urls.py
from django.urls import path 

from main import views
app_name = "appMain"


urlpatterns = [
    path('',views.mainViews,name='pageMain'),
    path('article/<int:articleId>/',views.article,name='pageArticle'),
    path('change-language/<str:language_code>/', views.change_language, name='change_language'),
    path('chatbotGpt2/', views.chatbotGpt2, name='chatbotGpt2'),
    path('chatbotRag/', views.chatbotRag, name='chatbotRag'),  # URL vers la vue chatbot
    path('upload/', views.upload_files, name='upload_files'),
]

multilang_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from multilang_site import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # On donne le chemin d'accès vers le dossier media pour que les images puisse être stocké dedans

main/models.py
from django.db import models
from django.utils import timezone 
# Create your models here.

class Articles(models.Model):
    title = models.CharField(max_length=128, default="") # On crée un champ title de type string avec 128 caractères maximum
    content = models.TextField(blank=True, default="") # On crée un champ content de type text
    publication_date = models.DateTimeField(default=timezone.now, blank=True) # On crée un champ publication_date de type DateTime qui prend la date et l'heure de la publication de l'article

    def __str__(self) -> str:
        return f"{self.title}" # Dans l'interface administration, on affiche les titles.

main/views.py
from django.shortcuts import render
from main.models import Articles
from django.shortcuts import redirect
from django.utils.translation import activate
from django.conf import settings
from django.http import JsonResponse
import json
from django.views.decorators.csrf import csrf_exempt
from .utils import process_query, vectorDocuments, addDocumentDB, chatbotLLM, translation
import os


# Create your views here.

# Si l'appllication est lancé pour la première, au démarage on télécharge le model de texte génération sinon on l'importe simplement.

collection_name = 'mycollection'

def chatbotGpt2(request): # Fonction du chatbot pour le model gpt2.
    """
    Gère les interactions avec le chatbot.

    Args:
        request (HttpRequest): La requête HTTP reçue, avec la question de l'utilisateur.

    Returns:
        JsonResponse: La réponse du chatbot sous forme JSON.
    """
    if request.method == 'POST': # On vérifie si la requête est de type Post.       
        user_message = request.POST.get("message")
        langueUser = request.LANGUAGE_CODE
        # langue = request
        if user_message: # Si on récupère bien le texte de l'utilisateur.
            # On le traduit en anglais pour qu'il soient compréhensible par le model gpt2:
            texteSortie = chatbotLLM(user_message, langueUser)
            return JsonResponse({'response': texteSortie}) # On retourne le texte en format json à la requête ajax du fichier script.js
        else:
            return JsonResponse({'error': 'Invalid request'}, status=400)
    else:
        return render(request, 'chatbot.html') 


def mainViews(request): # Page principal.
    """
    Affiche la page principal avec les articles.

    Args:
        request (HttpRequest): La requête HTTP reçue.

    Returns:
        render: La page main.html.
    """
    articles = Articles.objects.filter()
    return render(request, 'main.html', context={"article_liste":articles}) #crée la page de la liste des articles.

def article(request, articleId): # Page détail d'un article.
    """
    Affiche la page détail d'un article.

    Args:
        request (HttpRequest): La requête HTTP reçue, et l'id de l'article.

    Returns:
        render: La page article.html.
    """
    article = Articles.objects.get(id=articleId)
    return render(request, 'article.html', context={"article":article}) # Crée la page de la liste des articles.

def change_language(request, language_code): # On change la langue de l'application.
    """
    Gère le changement de langue de l'application par l'utilisateur.

    Args:
        request (HttpRequest): La requête HTTP reçue, avec la langue choisie par l'utilisateur.

    Returns:
        return: La même page avec la langue changé.
    """
    response = redirect(request.META.get('HTTP_REFERER', '/'))
    if language_code in dict(settings.LANGUAGES):
        activate(language_code)
        response.set_cookie(settings.LANGUAGE_COOKIE_NAME, language_code)
    return response



@csrf_exempt
def chatbotRag(request):
    """
    Gère les interactions avec le chatbot RAG.

    Args:
        request (HttpRequest): La requête HTTP reçue, avec une requête utilisateur dans le corps.

    Returns:
        JsonResponse: La réponse du chatbot sous forme JSON.
    """
    if request.method == 'POST':
        try:
            # Récupère et analyse les données JSON envoyées par l'utilisateur
            data = json.loads(request.body)
            user_query = data.get('query')

            # On récupère la langue de l'utilisateur 
            langueUser = request.LANGUAGE_CODE

            # Tradution du texte en Anglais :
            user_query = translation(user_query,Langue="en")
            
            # Traite la requête utilisateur et génère une réponse
            response = process_query(user_query, collection_name)
            
            # Tradution du texte dans la langue de l'utilisateur si besoin :
            if not langueUser == "en":
                response = translation(response,Langue=langueUser)

            return JsonResponse({'response': response})
        
        except json.JSONDecodeError:
            # Gère le cas où le JSON est invalide
            return JsonResponse({'error': 'Invalid JSON'}, status=400)
    
    # Affiche la page du chatbot si la méthode n'est pas POST
    return render(request, 'chatbotrag.html')



@csrf_exempt
def upload_files(request):
    """
    Gère l'upload de fichiers PDF et TXT pour traitement.

    Args:
        request (HttpRequest): La requête HTTP reçue, avec les fichiers à uploader.

    Returns:
        JsonResponse: Message de confirmation ou d'erreur.
    """
    if request.method == 'POST' and request.FILES.getlist('documents'):
        files = request.FILES.getlist('documents')
        allowed_extensions = ['.pdf', '.txt']
        file_paths = []

        # Vérifie que chaque fichier a une extension valide
        for file in files:
            if not any(file.name.endswith(ext) for ext in allowed_extensions):
                return JsonResponse({'error': 'Format de fichier invalide.Seuls les fichiers PDF et TXT sont permis.'}, status=400)

            # Enregistre chaque fichier dans le dossier 'uploads'
            path = os.path.join('uploads', file.name)
            with open(path, 'wb+') as destination:
                for chunk in file.chunks():
                    destination.write(chunk)
            file_paths.append(path)

        # Traite les fichiers uploadés
        chunks = vectorDocuments(file_paths)
        addDocumentDB(chunks, collection_name)
        
        # Renvoie une réponse de succès
        return JsonResponse({'message': 'Traitement réussi des fichiers.'}, status=200)
    
    # Affiche la page d'upload si la méthode n'est pas POST
    return render(request, 'upload.html')

templates/article.html
{% extends "base.html" %}  {% comment %} on etend le fichier base.html dans le dossier templates à la racine {% endcomment %}
{% load i18n %}
{% block content %} 

    <h2>{% trans "Titre article : " %} {{ article.title }}</h2>

    <p>{% trans "Contenus :" %}</p>
    <p>{{ article.content }}</p>
    <p>{% trans "Date de publication :" %}  {{ article.publication_date }}</p>

{% endblock %} 

{% block js %}
{% endblock %}

templates/base.html
{% load static %}
{% load i18n %}
<html>   
    <head>
        <meta charset="UTF-8">
        <title>Multilang APP DJANGO</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> 
        <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    </head>
    <body class="wrapper">
        <header>
            <nav class="navbar bg-body-tertiary"> 
                <a class="lienMenu" href="{% url 'appMain:pageMain' %}">Multilang Django</a> 
                <a class="lienMenu" href="{% url 'appMain:chatbotGpt2' %}">Chatbot</a> 
                <a class="lienMenu" href="{% url 'appMain:upload_files' %}">Upload</a> 
                <a class="lienMenu" href="{% url 'appMain:chatbotRag' %}">Chatbot Rag</a> 

                <div class="btn-group mx-auto p-2" role="group" aria-label="Basic example">
                    <a href="{% url 'appMain:change_language' 'fr' %}" class="btn btn-primary" >{% trans "Francais" %}</a>

                    <a href="{% url 'appMain:change_language' 'en' %}" class="btn btn-primary">{% trans "Anglais" %}</a>
                </div>
            </nav>
        </header>
        <main class="">
            <div class="container">
                {% block content %}

                {% endblock %}
            </div>  
        </main>
        <br>
        <footer class="footer mt-auto py-3 bg-body-tertiary">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><p class="px-2 text-body-secondary">Bilal BOUDJIDJ</p></li>
            <li class="nav-item"><p class="px-2 text-body-secondary">bilelboudjidj8@gmail.com</p></li>
            <li class="nav-item"><p class="px-2 text-body-secondary">0776396685</p></li>
            <li class="nav-item"><a href="https://github.com/Boudjidj-Bilal/DiotSiaci" target="_blank" class="px-2 text-body-secondary">Github</a></li>
            <li class="nav-item"><a href="https://www.linkedin.com/in/bilal-boudjidj-529638251/" class="px-2 text-body-secondary">Linkedin</a></li>
        </ul>
        <p class="text-center text-body-secondary">{% trans "L'application est hébergé sur une machine " %}<a class="text-body-secondary" target="_blank" href="https://cloud.digitalocean.com/">DigitalOcean.</a></p>
        <p class="text-center text-body-secondary">© 2024. {% trans "Merci à la company DiotSiaci de m'avoir permis d'effectuer ce test dans le cadre d'une alternance." %}</p>
        </footer>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
 
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

        <script src="{% static 'js/script.js' %}"></script>


        {% block js %}
        {% endblock %}

    </body>
</html>

templates/chatbot.html
{% extends "base.html" %}

{% load static %}

{% load i18n %}

{% block content %}
<center>
    <h1>{% trans "Model hébergé localement chatgpt2 :"%}</h1>
    <br>
    <div id="chat-log">        

    </div>
    <form method="POST"  action="">
        {% csrf_token %}
        <br>
        <input class="form-control shadow-sm" placeholder="Message" id="userinput" type="text" name="message">

        <br>
    </form>
    <button class="btn btn-primary" onclick="chatbot()">{% trans "Entrer"%}
    </button>
    <br>
    <br>
    <p>{% trans "Voici un chatbot qui utilise le model chatgpt2. Par soucis d'espace disque, je n'ai pas pu installer un model puissant. Le chatbot ne fonctionne donc pas très bien."%}</p>
</center>
{% endblock %}

{% block js %}

{% endblock %}

templates/chatbotrag.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Chatbot RAG{% endblock %}

{% block content %}
<h5>Chat avec RAG LLM</h5>

<div class="chat-box mt-3 p-3 border">
    <div id="chat-log" class="mb-3" style="height: 300px; overflow-y: auto;"></div>
    <textarea id="chat-input" class="form-control mb-2 shadow-sm" rows="3" placeholder="Type your message..."></textarea>
    

    <button  id="send-btn" type="submit"class="btn btn-primary mt-2" type="button"> Envoyer...
          <span   id="chatbot-spinner"  style="display: none;">  <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true" ></span></span>
    </button>

</div>


{% endblock %}

{% block js %}
<script src="{% static 'js/chatbot.js' %}"></script>
{% endblock %}

templates/main.html
{% extends "base.html" %}  {% comment %} on etend le fichier base.html dans le dossier templates à la racine {% endcomment %}
{% load i18n %}
{% block content %} 
 
    <h2 class="pb-2 border-bottom py-3">{% trans "Liste article : " %}</h2> 
    <div class="d-flex justify-content-evenly contentCard">
        {% for article in article_liste %}  
        <div class="card shadow" style="width: 18rem;">
            <div class="card-body">
            <h5 class="card-title">{{ article.title }}</h5>
            <p class="card-text text-truncate" style="max-width: 200px;">{{ article.content }}</p>
            <a href="{% url 'appMain:pageArticle' article.id %}">{{ article.title }}</a>
            </div>
        </div>
        {% endfor %}
    </div>
    <p class="pyt-1">{% trans "Gérer les "%}<a target="_blank" href="{% url 'admin:index' %}">articles</a>.</p>
{% endblock %} 

{% block js %}
{% endblock %}

templates/upload.html

{% extends 'base.html' %}
{% load static %}
{% block title %}Téléverser Fichiers{% endblock %}

{% block content %}
<h5>Téléverser des fichiers PDF et Text</h5>
<form id="upload-form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group mt-3">
        <label for="files">Sélectionner des fichiers en anglais:</label>
        <input type="file" class="form-control shadow-sm" id="files" name="files" accept=".pdf,.txt" multiple required>
        <div id="file-error" class="text-danger mt-1"></div>

    </div>


        <button type="submit"class="btn btn-primary mt-2" type="button"> Transferer...
          <span  id="upload-spinner"  style="display: none;">  <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true" ></span></span>
        </button>

</form>

<div id="upload-message" class="mt-3"></div>



{% if uploaded_files %}
    <h3 class="mt-4">Televerser les Fichiers</h3>
    <ul>
        {% for file in uploaded_files %}
            <li>{{ file }}</li>
        {% endfor %}
    </ul>
{% endif %}

{% endblock %}


{% block js %}
<script src="{% static 'js/uploadfiles.js' %}"></script>
{% endblock %}
